### ISSUE TITLE
Error in compiling examples

### ISSUE THREAD

**Issue by Stinde** [odelot/aws-mqtt-websockets#26]
When compiling the examples, I get error about HASH_HEX_LEN2 has already defined in AWSClient2.h

I have latest aws-sdk-arduino and Arduino IDE 1.6.12.

**Comment by odelot** [comment]
Sorry, I removed this dependencie but forgot to update the examples.

Remove the include for AWSClient2.h

**Comment by Stinde** [comment]
Now it's compiling without errors, thanks.
