### ISSUE TITLE
A whole lot of problems

### ISSUE THREAD

**Issue by Ravoos** [odelot/aws-mqtt-websockets#36]
Hey. I have a problem on using this code in Arduino. I get these messages:
Arduino:1.8.4 (Windows 10), Kort:"Adafruit HUZZAH ESP8266, 80 MHz, 4M (1M SPIFFS), v2 Prebuilt (MSS=536), Disabled, None, 115200"

C:\Program Files (x86)\Arduino\libraries\aws-mqtt-websockets\AWSWebSocketClient.cpp: In member function 'char* AWSWebSocketClient::generateAWSPath(uint16_t)':

C:\Program Files (x86)\Arduino\libraries\aws-mqtt-websockets\AWSWebSocketClient.cpp:277:2: error: 'SHA256' was not declared in this scope

  SHA256* sha256 = new SHA256();

  ^

C:\Program Files (x86)\Arduino\libraries\aws-mqtt-websockets\AWSWebSocketClient.cpp:277:10: error: 'sha256' was not declared in this scope

  SHA256* sha256 = new SHA256();

          ^

C:\Program Files (x86)\Arduino\libraries\aws-mqtt-websockets\AWSWebSocketClient.cpp:277:23: error: expected type-specifier before 'SHA256'

  SHA256* sha256 = new SHA256();

                       ^

C:\Program Files (x86)\Arduino\libraries\aws-mqtt-websockets\AWSWebSocketClient.cpp:277:23: error: expected ';' before 'SHA256'

C:\Program Files (x86)\Arduino\libraries\aws-mqtt-websockets\AWSWebSocketClient.cpp:279:9: error: type '<type error>' argument given to 'delete', expected pointer

  delete sha256;

         ^

C:\Program Files (x86)\Arduino\libraries\aws-mqtt-websockets\AWSWebSocketClient.cpp:287:15: error: expected type-specifier before 'SHA256'

  sha256 = new SHA256();

               ^

C:\Program Files (x86)\Arduino\libraries\aws-mqtt-websockets\AWSWebSocketClient.cpp:287:15: error: expected ';' before 'SHA256'

C:\Program Files (x86)\Arduino\libraries\aws-mqtt-websockets\AWSWebSocketClient.cpp:289:9: error: type '<type error>' argument given to 'delete', expected pointer

  delete sha256;

         ^

C:\Program Files (x86)\Arduino\libraries\aws-mqtt-websockets\AWSWebSocketClient.cpp:303:64: error: 'hmacSha256' was not declared in this scope

     char* k1 = hmacSha256(key, keyLen, awsDate, strlen(awsDate)); 

                                                                ^

C:\Program Files (x86)\Arduino\libraries\aws-mqtt-websockets\AWSWebSocketClient.cpp:305:31: error: 'SHA256_DEC_HASH_LEN' was not declared in this scope

     char* k2 = hmacSha256(k1, SHA256_DEC_HASH_LEN, awsRegion,

                               ^

exit status 1
Error compiling for board Adafruit HUZZAH ESP8266.

This happens when I try to verify or load it up to my Adafuit. Do you know why this is happening?

**Comment by odelot** [comment]
did you get all the dependencies? sha256 is found here https://github.com/odelot/aws-sdk-arduino

you need these 3 libraries  ([1](https://github.com/odelot/aws-sdk-arduino), [2](https://github.com/Links2004/arduinoWebSockets) and [3](https://github.com/knolleary/pubsubclient))
