### ISSUE TITLE
Compiles by the console prints gibberish

### ISSUE THREAD

**Issue by tejaswigowda** [odelot/aws-mqtt-websockets#8]
I see non ascii characters when I connect to the mcu (via screen) after running this. I have installed all dependencies and the program compiles perfectly.

I am new to this library. Any ideas?

**Comment by tejaswigowda** [comment]
It may have something to do with the baud rate. Any suggestions?

**Comment by odelot** [comment]
have you fixed this? it was baud rate misconfiguration? can we close this one?
